#ifndef QCOMPLUTERINFO_GLOBAL_H
#define QCOMPLUTERINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QCOMPUTERINFO_LIBRARY)
#  define QCOMPUTERINFOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QCOMPUTERINFOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QCOMPUTERINFO_GLOBAL_H
