#ifndef QENCRYPTIONKIT_GLOBAL_H
#define QENCRYPTIONKIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QENCRYPTIONKIT_LIBRARY)
#  define QENCRYPTIONKITSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QENCRYPTIONKITSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QENCRYPTIONKIT_GLOBAL_H
